### ISSUE TITLE
IMU & Frame timestamps

### ISSUE THREAD

**Issue by nsk126** [Perception-Solutions/OpenCamera-Sensors#2]
If there a way to have files generated in "Time since epoch" format than the standard format being used as timestamps for IMU and frames now?

**Comment by TimPushkin** [comment]
No, currently there is not. And I don't think it is useful to implement if you are talking about using [`System.currentTimeMillis()`](https://developer.android.com/reference/java/lang/System#currentTimeMillis()) as timestamps.

I think so because there are several issues with `System.currentTimeMillis`:
1. It is a wall clock meaning it is not monotonic. I believe, it can be changed even without you noticing (e.g. by automatic network time synchronization) and you'll get your timestamps jumping back and forth.
2. Android only provides IMU and frame timestamps (latter only if the smartphone supports it) in the `SystemClock.elapsedRealtime()` time domain which, I believe, is not possible to easily convert into the `currentTimeMillis` domain. If instead we will gather our own timestamps in code, these won't be the actual timestamps as they can only be gathered after the event occurs and, most likely, there won't be a constant difference from the actual timestamps.

**Comment by TimPushkin** [comment]
If you need this to get comparable timestamps among different devices you can try synchronized recording with RecSync functionality: https://github.com/prime-slam/OpenCamera-Sensors#synchronized-recording-on-multiple-smartphones-recsync

**Comment by nsk126** [comment]
> No, currently there is not. And I don't think it is useful to implement if you are talking about using [`System.currentTimeMillis()`](https://developer.android.com/reference/java/lang/System#currentTimeMillis()) as timestamps.
> 
> I think so because there are several issues with `System.currentTimeMillis`:
> 
> 1. It is a wall clock meaning it is not monotonic. I believe, it can be changed even without you noticing (e.g. by automatic network time synchronization) and you'll get your timestamps jumping back and forth.
> 2. Android only provides IMU and frame timestamps (latter only if the smartphone supports it) in the `SystemClock.elapsedRealtime()` time domain which, I believe, is not possible to easily convert into the `currentTimeMillis` domain. If instead we will gather our own timestamps in code, these won't be the actual timestamps as they can only be gathered after the event occurs and, most likely, there won't be a constant difference from the actual timestamps.

Would it be fine to get `System.currentTimeMillis` based values like,
```
long elapsedRealtime = SystemClock.elapsedRealtime();
long currentTimeMillis = System.currentTimeMillis() + (elapsedRealtime - SystemClock.uptimeMillis());
```
every iteration?

**Comment by TimPushkin** [comment]
I don't really understand how `long currentTimeMillis = System.currentTimeMillis() + (elapsedRealtime - SystemClock.uptimeMillis());` should work. As I understand, the difference between `SystemClock.elapsedRealtime()` and `SystemClock.uptimeMillis()` is the time the system spent sleeping since the last boot. And also, this all should be in nanoseconds if the formula is intended for IMU and frame timestamps which are in nanoseconds.

I think, it should be like this:
```java
long currentTimeBasedTimestempNanos = System.currentTimeMillis() * 1000000 - (SystemClock.elapsedRealtimeNanos() - elapsedRealtimeBasedTimestempNanos);
```

This formula assumes that `System.currentTimeMillis()` and `SystemClock.elapsedRealtimeNanos()` get calculated simultaneously. Then `(SystemClock.elapsedRealtimeNanos() - elapsedRealtimeBasedTimestempNanos)` gives the duration passed since the timestamp was captured and by subtracting it from `System.currentTimeMillis() * 1000000` we get the `currentTimeMillis`-based timestamp in nanoseconds.

But firstly, the assumption above may not always be true: an unknown amount of time may pass between calculating `System.currentTimeMillis()` and `SystemClock.elapsedRealtime()`. Secondly, you can see that `System.currentTimeMillis()` can be million times less precise than the actual timestamps -- I believe this can be somewhat ignored for frames since the smartphones usually capture them at around 60 Hz which is ~16 ms period between the captures, but IMUs can be much faster. And finally, again, getting timestamps in the `System.currentTimeMillis()` base is not a great idea because this way the timestamps may jump back and forth.

**Comment by nsk126** [comment]
I understand how there could be a time desync between the 2 functions. I had assumed we could use `System.currentTimeMillis()` once during recording, store it as a common var and use `SystemClock.elapsedRealtime()` as an accumulator that starts from 0 (could be done by recording the first value when recording and offsetting all of the following ones by that value). And print the offseted `elapsedRealtime()` shifted by `currentTimeMillis()`. Since `currentTimeMillis()` is being used only once, it should have less issue right? 

Although, i believe you mentioned 

> But firstly, the assumption above may not always be true: an unknown amount of time may pass between calculating System.currentTimeMillis() and SystemClock.elapsedRealtime()

Would be a major issue?

**Comment by TimPushkin** [comment]
If this suits your use case than it seems to me like it should work, yes. The resulting timestamps won't be in the "current" `System.currentTimeMillis()` time domain (since, theoretically, this domain can change during the recording), but they will be in the domain of the `System.currentTimeMillis()` value that was captured at the beginning of the recording.

> Although, i believe you mentioned
> 
> > But firstly, the assumption above may not always be true: an unknown amount of time may pass between calculating
> > System.currentTimeMillis() and SystemClock.elapsedRealtime()
> 
> Would be a major issue?

Yes, we would need to somehow simultaneously capture two timestamps -- `System.currentTimeMillis()` and `SystemClock.elapsedRealtime()` (again, these should actually be in nanoseconds, but I'll drop this to be short) -- in the beginning of the recording. To make this more prescise I can think of something like this (pseudo code):

```
desiredPrecisionMs = 1;

do {
    elapsedRealtime1 = SystemClock.elapsedRealtime();
    currentTime = System.currentTimeMillis();
    elapsedRealtime2 = SystemClock.elapsedRealtime();

    elapsedRealtime = elapsedRealtime1 / 2 + elapsedRealtime2 / 2;  // Division before sum just to avoid overflow

    maxErrorMs = (elapsedRealtime2 - elapsedRealtime1) / 2;
} while (maxErrorMs > desiredPrecisionMs)

// Use currentTime and elapsedRealtime as the same timestamp in the corresponding time domains
```

Anyway, I don't think we will implement this in OpenCamera Sensors as it seems to suite a pretty narrow set of use cases.

**Comment by nsk126** [comment]
I believe that explains it. I'll try out this approach and test how accurate the timestamps are. However, I don't hope for much.

If results are indeed good, I'll share it here. Either way, Thanks for helping out. I think we can close the issue now.
